from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from datetime import datetime
import os


def generate_tender_pdf(data: dict, output_path="generated_pdfs/quotation.pdf"):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="Small",
        fontSize=9,
        textColor=HexColor("#475569")
    ))

    elements = []

    # ---------- COLORS ----------
    PRIMARY = HexColor("#1E3A8A")
    ACCENT = HexColor("#2563EB")
    LIGHT_BG = HexColor("#EFF6FF")
    GREEN = HexColor("#16A34A")
    RED = HexColor("#DC2626")
    YELLOW = HexColor("#CA8A04")

    # ---------- HEADER ----------
    elements.append(Paragraph(
        "<b><font size=20 color='#1E3A8A'>BID QUOTATION</font></b>",
        styles["Title"]
    ))

    elements.append(Spacer(1, 6))

    elements.append(Paragraph(
        "<font size=11>Generated by <b>Agentic AI – B2B RFP Automation Platform</b></font>",
        styles["Normal"]
    ))

    elements.append(Spacer(1, 14))

    rfp = data.get("rfp_summary", {})
    pricing = data.get("pricing", {})

    elements.append(Paragraph(
        f"""
        <b>Bid Date:</b> {datetime.now().strftime('%d %B %Y')}<br/>
        <b>Product Category:</b> {rfp.get('product_family', 'N/A')}<br/>
        <b>Voltage Grade:</b> {rfp.get('voltage_grade', 'N/A')}
        """,
        styles["Normal"]
    ))

    elements.append(Spacer(1, 20))

    # ---------- TECHNICAL TABLE ----------
    elements.append(Paragraph("<b>Technical Recommendations</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    tech_table_data = [["SKU", "Specification Match (%)"]]

    for r in data.get("technical_recommendations", []):
        tech_table_data.append([
            r.get("sku", ""),
            f"{r.get('spec_match_percent', 0)}%"
        ])

    tech_table = Table(tech_table_data, colWidths=[300, 150])
    tech_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("GRID", (0, 0), (-1, -1), 0.5, black),
        ("BACKGROUND", (0, 1), (-1, -1), LIGHT_BG),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(tech_table)
    elements.append(Spacer(1, 18))

    # ---------- PRICING TABLE ----------
    elements.append(Paragraph("<b>Pricing Summary</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    price_data = [["SKU", "Unit Price (₹/m)", "Quantity (m)", "Total Cost (₹)"]]

    for p in pricing.get("products", []):
        price_data.append([
            p.get("sku", ""),
            f"{p.get('unit_price', 0):,}",
            p.get("quantity", 0),
            f"{p.get('cost', 0):,}"
        ])

    price_data.append(["", "", "Material Cost", f"{pricing.get('material_cost', 0):,}"])
    price_data.append(["", "", "Test Cost", f"{pricing.get('test_cost', 0):,}"])
    price_data.append(["", "", "TOTAL BID VALUE", f"{pricing.get('total_cost', 0):,}"])

    price_table = Table(price_data, colWidths=[200, 100, 90, 100])
    price_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("GRID", (0, 0), (-1, -1), 0.5, black),
        ("BACKGROUND", (0, 1), (-1, -4), LIGHT_BG),
        ("SPAN", (0, -1), (1, -1)),
        ("BACKGROUND", (-2, -1), (-1, -1), ACCENT),
        ("TEXTCOLOR", (-2, -1), (-1, -1), white),
        ("FONTNAME", (-2, -1), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
    ]))

    elements.append(price_table)
    elements.append(Spacer(1, 20))

    # ---------- CONFIDENCE ----------
    confidence = data.get("confidence", "LOW").upper()

    confidence_color = {
        "HIGH": GREEN,
        "MEDIUM": YELLOW,
        "LOW": RED
    }.get(confidence, RED)

    elements.append(Paragraph(
        f"<b>Bid Confidence:</b> <font color='{confidence_color.hexval()}'>{confidence}</font>",
        styles["Heading3"]
    ))

    elements.append(Spacer(1, 30))

    # ---------- FOOTER ----------
    elements.append(Paragraph(
        "This is a system-generated quotation intended for tender evaluation and demonstration purposes only.",
        styles["Small"]
    ))

    doc.build(elements)
    return output_path
